default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV['DB_USER'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  host: <%= ENV['DB_HOST'] %>
  socket: /var/run/mysqld/mysqld.sock

development:
  <<: *default
  database: <%= ENV['DB_NAME'] || 'my_database_development' %>

test:
  <<: *default
  database: <%= ENV['DB_NAME'] || 'my_database_test' %>

production:
  <<: *default
  database: <%= ENV['DB_NAME'] || 'my_database_production' %>
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>